# Change this to your own values and rename the file to .env
HASS_HOST=https://tzednkdhabksfyxxhtycpcy6rumhiri8.ui.nabu.casa
HASS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3ODM0OGUxYjA2ZWY0ZjM5YjBjMjBmZGNhMWY0MGQ3MCIsImlhdCI6MTczMDkwNzgxOCwiZXhwIjoyMDQ2MjY3ODE4fQ.iB2ixMVF5-JSNkiEPNhF8VWh4ho55fbDSQfs173acNM
STREAMDECK_CONFIG=/homeassistant/custom_components/streamdeck/configuration.yaml
WEBSOCKET_PROTOCOL=wss
